#ifndef COMMON_LIBSERVICE_H
#define COMMON_LIBSERVICE_H



#define NUMBER_STR_LENGTH 10
#define NAME_STR_LENTH_FOR_ELEMENT 80
#define NAME_STR_LENTH_FOR_ELEMENT 80

using namespace alex;

#endif // COMMON_LIBSERVICE_H
